config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get 'about', to: 'pages#about'
  
  resources :account_lookups, only: [:index, :create]
  resources :users
  resources :keywords
  resources :filters

end

app/models/account_lookup.rb
class AccountLookup
  attr_accessor :screen_name, :name, :user_guid, :profile_background_image_url, :followers_count, :error_message
  
    def initialize(options = {})
        unless options.nil?
          @screen_name ||= options[:screen_name]
          @name ||= options[:name]
          @user_guid = options[:user_guid]
          @profile_background_image_url = options[:profile_background_image_url]
          @followers_count = options[:followers_count]
          @error_message = options[:error_message]
        end        
    end
    
    def update_details_from_twitter
      
      unless @screen_name.empty?
        begin
          client = twitter_api_client
          twitter_user = client.user(@screen_name)
        rescue Twitter::Error => e
          Rails.logger.error "message:    #{e.message}"
          Rails.logger.error "backtrace:  #{e.backtrace.inspect}"
          Rails.logger.error "code:       #{e.code}"
          Rails.logger.error "rate limit: #{e.rate_limit.inspect}"
          Rails.logger.error "exception:  #{e.exception}"
          @error_message = e.message
        rescue Exception => e  
          Rails.logger.error e.message  
          Rails.logger.error e.backtrace.inspect 
        end
        
        if twitter_user.is_a?(Twitter::User)
          @screen_name = twitter_user.screen_name
          @name = twitter_user.name
          @user_guid = twitter_user.id
          @profile_background_image_url = twitter_user.profile_background_image_url
          @followers_count = twitter_user.followers_count
        end
      end
      
      return self
    end 
  
    private
    
      def twitter_api_client
        twitter_yaml = YAML.load_file(File.expand_path("../../../config/twitter_api.yml", __FILE__))
        twitter_config = twitter_yaml[Rails.env]
        Twitter::REST::Client.new do |config|
          config.consumer_key        = twitter_config["api_key"]
          config.consumer_secret     = twitter_config["api_secret"]
          config.access_token        = twitter_config["oauth_access_token"]
          config.access_token_secret = twitter_config["oauth_access_token_secret"]
        end        
      end
  
  
end

app/models/filter.rb
class Filter < ActiveRecord::Base
  belongs_to :user
  
  validates :filter_value, presence: true
  
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  belongs_to :user
  
  validates :keyword_value, presence: true
  
end

app/models/raw_tweet.rb
class RawTweet < ActiveRecord::Base
  
  validates :raw, presence: true
  validates :tweet_guid, presence: true
   
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :keyword, dependent: :destroy
  has_one :filter, dependent: :destroy
  
  validates :screen_name, presence: true
  
  after_save :assign_keyword
  after_save :assign_filter
  
  private
  
    def assign_keyword
      if self.keyword.nil?
        create_keyword!(keyword_value: "@"+self.screen_name.to_s)
      else
        self.keyword.keyword_value = "@"+self.screen_name.to_s
        self.keyword.save
      end 
    end
    
    def assign_filter
      if self.filter.nil?
        create_filter!(filter_value: self.user_guid)
      else
        self.filter.filter_value = self.user_guid
        self.filter.save
      end 
    end
    
end

app/controllers/account_lookups_controller.rb
class AccountLookupsController < ApplicationController
    
  # GET /account_lookups
  def index
    @account_lookup = AccountLookup.new
  end

  # POST /account_lookups
  def create
    @account_lookup = AccountLookup.new(account_lookup_params)
    @account_lookup.update_details_from_twitter
    flash.now[:error] = @account_lookup.error_message unless @account_lookup.error_message.nil?
    render :index
  end
  
  private
    # Only allow a trusted parameter "white list" through.
    def account_lookup_params
      params.require(:account_lookup).permit(:screen_name)
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  before_action :set_filter, only: [:show, :edit, :update, :destroy]

  # GET /filters
  def index
    @filters = Filter.all
  end

  # GET /filters/1
  def show
  end

  # GET /filters/new
  def new
    @filter = Filter.new
  end

  # GET /filters/1/edit
  def edit
  end

  # POST /filters
  def create
    @filter = Filter.new(filter_params)

    if @filter.save
      redirect_to @filter, notice: 'Filter was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /filters/1
  def update
    if @filter.update(filter_params)
      redirect_to @filter, notice: 'Filter was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /filters/1
  def destroy
    @filter.destroy
    redirect_to filters_url, notice: 'Filter was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filter
      @filter = Filter.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def filter_params
      params.require(:filter).permit(:filter_value, :user_id)
    end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]

  # GET /keywords
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  def create
    @keyword = Keyword.new(keyword_params)

    if @keyword.save
      redirect_to @keyword, notice: 'Keyword was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /keywords/1
  def update
    if @keyword.update(keyword_params)
      redirect_to @keyword, notice: 'Keyword was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /keywords/1
  def destroy
    @keyword.destroy
    redirect_to keywords_url, notice: 'Keyword was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def keyword_params
      params.require(:keyword).permit(:keyword_value, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/raw_tweets_controller.rb
class RawTweetsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:name, :screen_name, :user_guid, :followers_count, :profile_background_image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/account_lookups/index.html.erb
    <div class="container">

      <%= bootstrap_flash %>
      
      <div class="row">
        
        <div class="col-md-9 main_content">
          <h2>New account lookup</h2>
          <%= form_tag("/account_lookups", method: "post") do %>
            <%= label_tag(:screen_name, "Screen Name") %>
            <%= text_field_tag("account_lookup[screen_name]") %>
            <%= submit_tag("Lookup") %>
          <% end %>
          <hr>
          <p><%= @account_lookup.inspect %></p>
          <hr>
          <p>Screen Name: <%= @account_lookup.screen_name %></p>
          <p>Name: <%= @account_lookup.name %></p>
          <p>User GUID <%= @account_lookup.user_guid %></p>
          <p>Profile Background Image URL: <%= @account_lookup.profile_background_image_url %></p>
          <p>Followers Count: <%= @account_lookup.followers_count %></p>
          <%= form_tag("/users", method: "post") do %>
            <%= hidden_field_tag("user[screen_name]", @account_lookup.screen_name) %>
            <%= hidden_field_tag("user[name]", @account_lookup.name) %>
            <%= hidden_field_tag("user[user_guid]", @account_lookup.user_guid) %>
            <%= hidden_field_tag("user[profile_background_image_url]", @account_lookup.profile_background_image_url ) %>
            <%= hidden_field_tag("user[followers_count]", @account_lookup.followers_count) %>
            <%= submit_tag("Save") %>
          <% end %>  
          <hr>
        </div>
        <div class="col-md-3 sidebar">
          <%= render "shared/sidebar_nav" %>
        </div>
        
      </div>
      
      <hr>
      <%= render "shared/footer" %>
    </div> <!-- /container -->

app/views/account_lookups/new.html.erb
    <div class="container">

      <%= bootstrap_flash %>
      
      <div class="row">
        
        <div class="col-md-9 main_content">
          <h2>New account lookup</h2>
          <%= form_tag("/account_lookups", method: "post") do %>
            <%= label_tag(:name, "Name") %>
            <%= text_field_tag("account_lookup[name]") %>
            <%= submit_tag("Lookup") %>
          <% end %>
          <hr>
          <p><%= @account_lookup.inspect %></p>
          <hr>
          <p>Name: <%= @account_lookup.name %></p>
          <p>Screen Name: <%= @account_lookup.screen_name %></p>
          <p>User GUID <%= @account_lookup.user_guid %></p>
          <p>Profile Background Image URL: <%= @account_lookup.profile_background_image_url %></p>
          <p>Followers Count: <%= @account_lookup.followers_count %></p>
          
            
          <hr>
        </div>
        <div class="col-md-3 sidebar">
          <div class="well sidebar-nav">
            <h3>Navigation</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "New Account", new_account_lookups_path %></li> 
            </ul>
          </div>  
        </div>
        
      </div>
      
      <hr>

      <footer>
        <p>&copy; Company 2014</p>
        <%= debug params %>
      </footer>
    </div> <!-- /container -->

app/views/filters/_form.html.erb
<%= form_for(@filter) do |f| %>
  <% if @filter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filter.errors.count, "error") %> prohibited this filter from being saved:</h2>

      <ul>
      <% @filter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filter_value %><br>
    <%= f.text_field :filter_value %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/filters/edit.html.erb
<h1>Editing filter</h1>

<%= render 'form' %>

<%= link_to 'Show', @filter %> |
<%= link_to 'Back', filters_path %>

app/views/filters/index.html.erb
<h1>Listing filters</h1>

<table>
  <thead>
    <tr>
      <th>Filter value</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @filters.each do |filter| %>
      <tr>
        <td><%= filter.filter_value %></td>
        <td><%= filter.user_id %></td>
        <td><%= link_to 'Show', filter %></td>
        <td><%= link_to 'Edit', edit_filter_path(filter) %></td>
        <td><%= link_to 'Destroy', filter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Filter', new_filter_path %>

app/views/filters/new.html.erb
<h1>New filter</h1>

<%= render 'form' %>

<%= link_to 'Back', filters_path %>

app/views/filters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filter value:</strong>
  <%= @filter.filter_value %>
</p>

<p>
  <strong>User:</strong>
  <%= @filter.user_id %>
</p>

<%= link_to 'Edit', edit_filter_path(@filter) %> |
<%= link_to 'Back', filters_path %>

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :keyword_value %><br>
    <%= f.text_field :keyword_value %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<h1>Listing keywords</h1>

<table>
  <thead>
    <tr>
      <th>Keyword value</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= keyword.keyword_value %></td>
        <td><%= keyword.user_id %></td>
        <td><%= link_to 'Show', keyword %></td>
        <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
        <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keyword', new_keyword_path %>

app/views/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keyword value:</strong>
  <%= @keyword.keyword_value %>
</p>

<p>
  <strong>User:</strong>
  <%= @keyword.user_id %>
</p>

<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><%= content_for?(:title) ? yield(:title) : "AFL Real-Time" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">AFL Real-Time</a>
        </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>
    
    <%= yield %>
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/about.html.erb
    <div class="container">

      <%= bootstrap_flash %>
      
      <div class="row">
        
        <div class="col-md-9 main_content">
          <h2>Pages#about</h2>
          <p>Find me in app/views/pages/about.html.erb</p>
            
          <hr>
        </div>
        <div class="col-md-3 sidebar">
          <div class="well sidebar-nav">
            <h3>Navigation</h3>
            <ul class="nav nav-list">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", about_path %></li>
              <li><%= link_to "Follow New Account", account_lookups_path %></li> 
            </ul>
          </div>  
        </div>
        
      </div>
      
      <hr>

      <footer>
        <p>&copy; Company 2014</p>
        <%= debug params %>
      </footer>
    </div> <!-- /container -->

app/views/pages/home.html.erb
    <div class="container">

      <%= bootstrap_flash %>
      
      <div class="row">
        
        <div class="col-md-9 main_content">
          <h2>Pages#home</h2>
          <p>Find me in app/views/pages/home.html.erb</p>
            
          <hr>
        </div>
        <div class="col-md-3 sidebar">
          <%= render "shared/sidebar_nav" %>
        </div>
        
      </div>
      
      <hr>
      <%= render "shared/footer" %>
    </div> <!-- /container -->

app/views/shared/_footer.html.erb
<footer>
  <p>&copy; Company 2014</p>
  <%= debug params %>
</footer>

app/views/shared/_sidebar_nav.html.erb
<div class="well sidebar-nav">
  <h3>Navigation</h3>
  <ul class="nav nav-list">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Follow New Account", account_lookups_path %></li>
    <li><%= link_to "Users", users_path %> </li>
  </ul>
</div>  

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :screen_name %><br>
    <%= f.text_field :screen_name %>
  </div>
  <div class="field">
    <%= f.label :user_guid %><br>
    <%= f.number_field :user_guid %>
  </div>
  <div class="field">
    <%= f.label :followers_count %><br>
    <%= f.number_field :followers_count %>
  </div>
  <div class="field">
    <%= f.label :profile_background_image_url %><br>
    <%= f.text_field :profile_background_image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
    <div class="container">

      <%= bootstrap_flash %>
      
      <div class="row">
        
        <div class="col-md-9 main_content">
          <h2>Editing user</h2>
          <%= render 'form' %>
          <%= link_to 'Show', @user %>
          <hr>
        </div>
        <div class="col-md-3 sidebar">
          <%= render "shared/sidebar_nav" %>
        </div>
        
      </div>
      
      <hr>

      <%= render "shared/footer" %>
    </div> <!-- /container -->

app/views/users/index.html.erb
    <div class="container">

      <%= bootstrap_flash %>
      
      <div class="row">
        
        <div class="col-md-9 main_content">
          
          <h2>Listing users</h2>

          <table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Screen name</th>
                <th>User guid</th>
                <th>Followers count</th>
                <th>Profile background image url</th>
                <th colspan="3"></th>
              </tr>
            </thead>
          
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td><%= user.name %></td>
                  <td><%= user.screen_name %></td>
                  <td><%= user.user_guid %></td>
                  <td><%= user.followers_count %></td>
                  <td><%= user.profile_background_image_url %></td>
                  <td><%= link_to 'Show', user %></td>
                  <td><%= link_to 'Edit', edit_user_path(user) %></td>
                  <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>         
          <hr>
        </div>
        <div class="col-md-3 sidebar">
          <%= render "shared/sidebar_nav" %>
        </div>
        
      </div>
      
      <hr>

      <%= render "shared/footer" %>
    </div> <!-- /container -->

app/views/users/new.html.erb
    <div class="container">

      <%= bootstrap_flash %>
      
      <div class="row">
        
        <div class="col-md-9 main_content">
          <h2>New user</h2>
          <%= render 'form' %>
          <hr>
        </div>
        <div class="col-md-3 sidebar">
          <%= render "shared/sidebar_nav" %>
        </div>
        
      </div>
      
      <hr>

      <%= render "shared/footer" %>
    </div> <!-- /container -->

app/views/users/show.html.erb
    <div class="container">

      <%= bootstrap_flash %>
      
      <div class="row">
        
        <div class="col-md-9 main_content">
            <strong>Name:</strong>
            <%= @user.name %>
          </p>
          
          <p>
            <strong>Screen name:</strong>
            <%= @user.screen_name %>
          </p>
          
          <p>
            <strong>User guid:</strong>
            <%= @user.user_guid %>
          </p>
          
          <p>
            <strong>Followers count:</strong>
            <%= @user.followers_count %>
          </p>
          
          <p>
            <strong>Profile background image url:</strong>
            <%= @user.profile_background_image_url %>
          </p>
          
          <% unless @user.keyword.nil? %>
          
            <p>
              <strong>>> Keyword Value:</strong>
              <%= @user.keyword.keyword_value %>
            </p>
            
          <% end %>
          
          <% unless @user.filter.nil? %>
          
            <p>
              <strong>>> Filter Value:</strong>
              <%= @user.filter.filter_value %>
            </p>
            
          <% end %>
           
          <%= link_to 'Edit', edit_user_path(@user) %>
        </div>
        <div class="col-md-3 sidebar">
          <%= render "shared/sidebar_nav" %>
        </div>
        
      </div>
      
      <hr>

      <%= render "shared/footer" %>
    </div> <!-- /container -->